redis: &default
  adapter: redis
  url: redis://localhost:6379/1

production:
  adapter: postgresql
  #url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  #channel_prefix: sushi_rails_production

development: *default
test: *default
