development:
  host: 'sushirailsredis-001.qhabqe.0001.use1.cache.amazonaws.comxx'
  port: '6379'
test:
  host: 'localhost'
  port: '6379'
production:
  host: 'sushirailsredis-001.qhabqe.0001.use1.cache.amazonaws.com'
  port: '6379'
